events_receiver/config/routes.rb
EventsReceiver::Application.routes.draw do
  resources :events
end

events_receiver/app/models/event.rb
class Event < ActiveRecord::Base
end

events_receiver/app/models/events.rb
class Events < ActiveRecord::Base
end

events_receiver/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_filter :verify_authenticity_token, if: :json_request?

  def json_request?
    request.format.json?
  end
end

events_receiver/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        # format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        # format.html { render action: 'new' }
        format.json { render JSON: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:sid, :cid, :signature, :signature_gen, :signature_id, :signature_rev, :timestamp, :unified_event_id, :unified_event_ref, :unified_ref_time, :priority, :clas, :status, :src_ip, :dst_ip, :src_port, :dst_port, :icmp_type, :icmp_code, :ip_proto, :ip_ver, :ip_hlen, :ip_tos, :ip_len, :ip_id, :ip_flags, :ip_flags, :ip_off, :ip_ttl, :ip_csum, :last_modified, :last_uid, :abuse_queue, :abuse_sent)
    end
end

events_receiver/app/helpers/application_helper.rb
module ApplicationHelper
end

events_receiver/app/helpers/events_helper.rb
module EventsHelper
end

events_receiver/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sid %><br>
    <%= f.number_field :sid %>
  </div>
  <div class="field">
    <%= f.label :cid %><br>
    <%= f.number_field :cid %>
  </div>
  <div class="field">
    <%= f.label :signature %><br>
    <%= f.text_field :signature %>
  </div>
  <div class="field">
    <%= f.label :signature_gen %><br>
    <%= f.number_field :signature_gen %>
  </div>
  <div class="field">
    <%= f.label :signature_id %><br>
    <%= f.number_field :signature_id %>
  </div>
  <div class="field">
    <%= f.label :signature_rev %><br>
    <%= f.number_field :signature_rev %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br>
    <%= f.datetime_select :timestamp %>
  </div>
  <div class="field">
    <%= f.label :unified_event_id %><br>
    <%= f.number_field :unified_event_id %>
  </div>
  <div class="field">
    <%= f.label :unified_event_ref %><br>
    <%= f.number_field :unified_event_ref %>
  </div>
  <div class="field">
    <%= f.label :unified_ref_time %><br>
    <%= f.number_field :unified_ref_time %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :class %><br>
    <%= f.text_field :clas %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :src_ip %><br>
    <%= f.number_field :src_ip %>
  </div>
  <div class="field">
    <%= f.label :dst_ip %><br>
    <%= f.number_field :dst_ip %>
  </div>
  <div class="field">
    <%= f.label :src_port %><br>
    <%= f.number_field :src_port %>
  </div>
  <div class="field">
    <%= f.label :dst_port %><br>
    <%= f.number_field :dst_port %>
  </div>
  <div class="field">
    <%= f.label :icmp_type %><br>
    <%= f.number_field :icmp_type %>
  </div>
  <div class="field">
    <%= f.label :icmp_code %><br>
    <%= f.number_field :icmp_code %>
  </div>
  <div class="field">
    <%= f.label :ip_proto %><br>
    <%= f.number_field :ip_proto %>
  </div>
  <div class="field">
    <%= f.label :ip_ver %><br>
    <%= f.number_field :ip_ver %>
  </div>
  <div class="field">
    <%= f.label :ip_hlen %><br>
    <%= f.number_field :ip_hlen %>
  </div>
  <div class="field">
    <%= f.label :ip_tos %><br>
    <%= f.number_field :ip_tos %>
  </div>
  <div class="field">
    <%= f.label :ip_len %><br>
    <%= f.number_field :ip_len %>
  </div>
  <div class="field">
    <%= f.label :ip_id %><br>
    <%= f.number_field :ip_id %>
  </div>
  <div class="field">
    <%= f.label :ip_flags %><br>
    <%= f.number_field :ip_flags %>
  </div>
  <div class="field">
    <%= f.label :ip_flags %><br>
    <%= f.number_field :ip_flags %>
  </div>
  <div class="field">
    <%= f.label :ip_off %><br>
    <%= f.number_field :ip_off %>
  </div>
  <div class="field">
    <%= f.label :ip_ttl %><br>
    <%= f.number_field :ip_ttl %>
  </div>
  <div class="field">
    <%= f.label :ip_csum %><br>
    <%= f.number_field :ip_csum %>
  </div>
  <div class="field">
    <%= f.label :last_modified %><br>
    <%= f.datetime_select :last_modified %>
  </div>
  <div class="field">
    <%= f.label :last_uid %><br>
    <%= f.number_field :last_uid %>
  </div>
  <div class="field">
    <%= f.label :abuse_queue %><br>
    <%= f.text_field :abuse_queue %>
  </div>
  <div class="field">
    <%= f.label :abuse_sent %><br>
    <%= f.text_field :abuse_sent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

events_receiver/app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

events_receiver/app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Sid</th>
      <th>Cid</th>
      <th>Signature</th>
      <th>Signature gen</th>
      <th>Signature</th>
      <th>Signature rev</th>
      <th>Timestamp</th>
      <th>Unified event</th>
      <th>Unified event ref</th>
      <th>Unified ref time</th>
      <th>Priority</th>
      <th>Class</th>
      <th>Status</th>
      <th>Src ip</th>
      <th>Dst ip</th>
      <th>Src port</th>
      <th>Dst port</th>
      <th>Icmp type</th>
      <th>Icmp code</th>
      <th>Ip proto</th>
      <th>Ip ver</th>
      <th>Ip hlen</th>
      <th>Ip tos</th>
      <th>Ip len</th>
      <th>Ip</th>
      <th>Ip flags</th>
      <th>Ip flags</th>
      <th>Ip off</th>
      <th>Ip ttl</th>
      <th>Ip csum</th>
      <th>Last modified</th>
      <th>Last uid</th>
      <th>Abuse queue</th>
      <th>Abuse sent</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.sid %></td>
        <td><%= event.cid %></td>
        <td><%= event.signature %></td>
        <td><%= event.signature_gen %></td>
        <td><%= event.signature_id %></td>
        <td><%= event.signature_rev %></td>
        <td><%= event.timestamp %></td>
        <td><%= event.unified_event_id %></td>
        <td><%= event.unified_event_ref %></td>
        <td><%= event.unified_ref_time %></td>
        <td><%= event.priority %></td>
        <td><%= event.clas %></td>
        <td><%= event.status %></td>
        <td><%= event.src_ip %></td>
        <td><%= event.dst_ip %></td>
        <td><%= event.src_port %></td>
        <td><%= event.dst_port %></td>
        <td><%= event.icmp_type %></td>
        <td><%= event.icmp_code %></td>
        <td><%= event.ip_proto %></td>
        <td><%= event.ip_ver %></td>
        <td><%= event.ip_hlen %></td>
        <td><%= event.ip_tos %></td>
        <td><%= event.ip_len %></td>
        <td><%= event.ip_id %></td>
        <td><%= event.ip_flags %></td>
        <td><%= event.ip_flags %></td>
        <td><%= event.ip_off %></td>
        <td><%= event.ip_ttl %></td>
        <td><%= event.ip_csum %></td>
        <td><%= event.last_modified %></td>
        <td><%= event.last_uid %></td>
        <td><%= event.abuse_queue %></td>
        <td><%= event.abuse_sent %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

events_receiver/app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

events_receiver/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sid:</strong>
  <%= @event.sid %>
</p>

<p>
  <strong>Cid:</strong>
  <%= @event.cid %>
</p>

<p>
  <strong>Signature:</strong>
  <%= @event.signature %>
</p>

<p>
  <strong>Signature gen:</strong>
  <%= @event.signature_gen %>
</p>

<p>
  <strong>Signature:</strong>
  <%= @event.signature_id %>
</p>

<p>
  <strong>Signature rev:</strong>
  <%= @event.signature_rev %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @event.timestamp %>
</p>

<p>
  <strong>Unified event:</strong>
  <%= @event.unified_event_id %>
</p>

<p>
  <strong>Unified event ref:</strong>
  <%= @event.unified_event_ref %>
</p>

<p>
  <strong>Unified ref time:</strong>
  <%= @event.unified_ref_time %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @event.priority %>
</p>

<p>
  <strong>Class:</strong>
  <%= @event.clas %>
</p>

<p>
  <strong>Status:</strong>
  <%= @event.status %>
</p>

<p>
  <strong>Src ip:</strong>
  <%= @event.src_ip %>
</p>

<p>
  <strong>Dst ip:</strong>
  <%= @event.dst_ip %>
</p>

<p>
  <strong>Src port:</strong>
  <%= @event.src_port %>
</p>

<p>
  <strong>Dst port:</strong>
  <%= @event.dst_port %>
</p>

<p>
  <strong>Icmp type:</strong>
  <%= @event.icmp_type %>
</p>

<p>
  <strong>Icmp code:</strong>
  <%= @event.icmp_code %>
</p>

<p>
  <strong>Ip proto:</strong>
  <%= @event.ip_proto %>
</p>

<p>
  <strong>Ip ver:</strong>
  <%= @event.ip_ver %>
</p>

<p>
  <strong>Ip hlen:</strong>
  <%= @event.ip_hlen %>
</p>

<p>
  <strong>Ip tos:</strong>
  <%= @event.ip_tos %>
</p>

<p>
  <strong>Ip len:</strong>
  <%= @event.ip_len %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @event.ip_id %>
</p>

<p>
  <strong>Ip flags:</strong>
  <%= @event.ip_flags %>
</p>

<p>
  <strong>Ip flags:</strong>
  <%= @event.ip_flags %>
</p>

<p>
  <strong>Ip off:</strong>
  <%= @event.ip_off %>
</p>

<p>
  <strong>Ip ttl:</strong>
  <%= @event.ip_ttl %>
</p>

<p>
  <strong>Ip csum:</strong>
  <%= @event.ip_csum %>
</p>

<p>
  <strong>Last modified:</strong>
  <%= @event.last_modified %>
</p>

<p>
  <strong>Last uid:</strong>
  <%= @event.last_uid %>
</p>

<p>
  <strong>Abuse queue:</strong>
  <%= @event.abuse_queue %>
</p>

<p>
  <strong>Abuse sent:</strong>
  <%= @event.abuse_sent %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

events_receiver/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventsReceiver</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>